# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Game Settings
DISPLAY_SCREEN = True
SHOW_STATS = True
TITLE = "Cytomata"
WIDTH = 200
HEIGHT = 200
TILESIZE = 20
GAME_SPEED = 0.1 * TILESIZE / 40
# MAX_TIME = 10.0
TERMINAL_STEP = 8000
ACTION_MEANING = {0: "NOOP", 1: "UP", 2: "DOWN", 3: "LEFT", 4: "RIGHT"}

# Sprite Settings
NUM_RANDOM_PROXIES = 1
PROXY_SPEED = 45.0
PROXY_MAX_SPEED = 90.0
PROXY_FRICTION = 0.9
PROXY_IMG = 'mac2.png'
NUM_RANDOM_CYTES = 0
CYTE_IMG = 'epi3.png'
NUM_RANDOM_CANCERS = 1
CANCER_IMG = 'cancer2.png'
