# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Game Settings
DISPLAY_SCREEN = True
SHOW_STATS = True
TITLE = "Cytomata"
WIDTH = 400
HEIGHT = 400
FPS = 60
GAME_SPEED = 4
TILESIZE = 80
MAX_TIME = 10.0
ACTION_MEANING = {0: "NOOP", 1: "UP", 2: "DOWN", 3: "LEFT", 4: "RIGHT"}

# Sprite Settings
NUM_RANDOM_PROXIES = 1
PROXY_SPEED = 50.0
PROXY_MAX_SPEED = 90.0
PROXY_FRICTION = 0.9
PROXY_IMG = 'mac1.png'
NUM_RANDOM_CYTES = 0
CYTE_IMG = 'epi1.png'
NUM_RANDOM_CANCERS = 1
CANCER_IMG = 'cancer2.png'
